wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704562721.532645
    t:
      1:
      - 1
      - 11
      - 49
      - 50
      - 55
      - 105
      2:
      - 1
      - 11
      - 49
      - 50
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.10.13
      5: 0.16.1
      6: 4.36.2
      8:
      - 3
      - 5
      13: windows-amd64
